In [1]:
import numpy as np
import pandas as pd

#### Question 1  
What's the version of NumPy that you installed?

In [2]:
np.__version__

'1.21.2'

#### Question 2  
What's the version of Pandas?

In [3]:
pd.__version__

'1.3.2'

In [4]:
data = pd.read_csv('data.csv')

In [5]:
data.head(2)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Make               11914 non-null  object 
 1   Model              11914 non-null  object 
 2   Year               11914 non-null  int64  
 3   Engine Fuel Type   11911 non-null  object 
 4   Engine HP          11845 non-null  float64
 5   Engine Cylinders   11884 non-null  float64
 6   Transmission Type  11914 non-null  object 
 7   Driven_Wheels      11914 non-null  object 
 8   Number of Doors    11908 non-null  float64
 9   Market Category    8172 non-null   object 
 10  Vehicle Size       11914 non-null  object 
 11  Vehicle Style      11914 non-null  object 
 12  highway MPG        11914 non-null  int64  
 13  city mpg           11914 non-null  int64  
 14  Popularity         11914 non-null  int64  
 15  MSRP               11914 non-null  int64  
dtypes: float64(3), int64(5

In [7]:
data.describe().round(0)

Year  Engine HP  Engine Cylinders  Number of Doors  highway MPG  \
count  11914.0    11845.0           11884.0          11908.0      11914.0   
mean    2010.0      249.0               6.0              3.0         27.0   
std        8.0      109.0               2.0              1.0          9.0   
min     1990.0       55.0               0.0              2.0         12.0   
25%     2007.0      170.0               4.0              2.0         22.0   
50%     2015.0      227.0               6.0              4.0         26.0   
75%     2016.0      300.0               6.0              4.0         30.0   
max     2017.0     1001.0              16.0              4.0        354.0   

       city mpg  Popularity       MSRP  
count   11914.0     11914.0    11914.0  
mean       20.0      1555.0    40595.0  
std         9.0      1442.0    60109.0  
min         7.0         2.0     2000.0  
25%        16.0       549.0    21000.0  
50%        18.0      1385.0    29995.0  
75%        22.0      2009.0    42231.0  
max       137.0      5657.0  2065902.0

#### Question 3  
What's the average price of BMW cars in the dataset?

In [8]:
data[data['Make'] == 'BMW'].MSRP.describe()

count       334.000000
mean      61546.763473
std       27982.682153
min        4697.000000
25%       42300.000000
50%       51850.000000
75%       79725.000000
max      141200.000000
Name: MSRP, dtype: float64

In [9]:
data[data['Make'] == 'BMW'].MSRP.mean()

61546.76347305389

In [10]:
data.groupby('Make').MSRP.mean()

Make
Acura            3.488759e+04
Alfa Romeo       6.160000e+04
Aston Martin     1.979104e+05
Audi             5.345211e+04
BMW              6.154676e+04
Bentley          2.471693e+05
Bugatti          1.757224e+06
Buick            2.820661e+04
Cadillac         5.623132e+04
Chevrolet        2.835039e+04
Chrysler         2.672296e+04
Dodge            2.239006e+04
FIAT             2.267024e+04
Ferrari          2.382188e+05
Ford             2.739927e+04
GMC              3.049330e+04
Genesis          4.661667e+04
HUMMER           3.646441e+04
Honda            2.667434e+04
Hyundai          2.459704e+04
Infiniti         4.239421e+04
Kia              2.531017e+04
Lamborghini      3.315673e+05
Land Rover       6.782322e+04
Lexus            4.754907e+04
Lincoln          4.283983e+04
Lotus            6.918828e+04
Maserati         1.142077e+05
Maybach          5.462219e+05
Mazda            2.003938e+04
McLaren          2.398050e+05
Mercedes-Benz    7.147623e+04
Mitsubishi       2.124054e+04
Nissa

#### Question 4:  
Select a subset of cars after year 2015 (inclusive, i.e. 2015 and after).  
How many of them have missing values for Engine HP?

In [11]:
data2015plus = data[data['Year'] >= 2015]

In [12]:
data2015plus.head(1)

Make       Model  Year                Engine Fuel Type  Engine HP  \
32  FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   

    Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
32               4.0            MANUAL  rear wheel drive              2.0   

   Market Category Vehicle Size Vehicle Style  highway MPG  city mpg  \
32     Performance      Compact   Convertible           35        26   

    Popularity   MSRP  
32         819  27495

In [13]:
 data2015plus.tail(1)

Make Model  Year             Engine Fuel Type  Engine HP  \
11902  BMW    Z4  2016  premium unleaded (required)      335.0   

       Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
11902               6.0  AUTOMATED_MANUAL  rear wheel drive              2.0   

               Market Category Vehicle Size Vehicle Style  highway MPG  \
11902  Luxury,High-Performance      Compact   Convertible           24   

       city mpg  Popularity   MSRP  
11902        17        3916  66350

In [14]:
 data2015plus.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        0
Engine HP              51
Engine Cylinders        8
Transmission Type       0
Driven_Wheels           0
Number of Doors         5
Market Category      1324
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [15]:
 data2015plus['Engine HP'].isnull().sum()

51

#### Question 5

* Calculate the average "Engine HP" in the dataset.
* Use the fillna method and to fill the missing values in "Engine HP" with the mean value from the previous step.
* Now, calcualte the average of "Engine HP" again.
* Gas it changed?

Round both means before answering this questions. You can use the round function for that:  
print(round(mean_hp_before))  
print(round(mean_hp_after))

In [16]:
data2015plus['Engine HP'].describe()

count    5944.000000
mean      272.987719
std       109.117257
min        66.000000
25%       184.000000
50%       270.000000
75%       325.000000
max       750.000000
Name: Engine HP, dtype: float64

In [17]:
mean_hp_before = data2015plus['Engine HP'].mean()
mean_hp_before

272.98771870794076

In [18]:
data2015plus['Engine HP'].isnull().sum()

51

In [19]:
data2015plus['Engine HP'].fillna(value=mean_hp_before).isnull().sum()

0

In [20]:
mean_hp_after = data2015plus['Engine HP'].fillna(value=mean_hp_before).mean()
mean_hp_after

272.98771870794076

In [21]:
print(round(mean_hp_before))

273


In [22]:
print(round(mean_hp_after))

273


In [23]:
mean_hp_after - mean_hp_before

0.0

#### Question 6  

* Select all the "Rolls-Royce" cars from the dataset.
* Select only columns "Engine HP", "Engine Cylinders", "highway MPG".
* Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 7 rows).
* Get the underlying NumPy array. Let's call it X.
* Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
* Invert XTX.
* What's the sum of all the elements of the result?

Hint: if the result is negative, re-read the task one more time

In [24]:
rollsroyce = data[data['Make'] == 'Rolls-Royce'][['Engine HP','Engine Cylinders','highway MPG']].drop_duplicates()

In [25]:
rollsroyce

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [26]:
X = rollsroyce.values
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [27]:
X_T = X.T
X_T

array([[325., 563., 563., 563., 322., 453., 624.],
       [  8.,  12.,  12.,  12.,  12.,  12.,  12.],
       [ 15.,  19.,  21.,  20.,  15.,  19.,  21.]])

In [28]:
XTX = X_T.dot(X)
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [29]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [30]:
XTX_inv.sum()

0.03221232067748617

#### Question 7

* Create an array y with values [1000, 1100, 900, 1200, 1000, 850, 1300].
* Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
* What's the value of the first element of w?.

Note: You just implemented linear regression. We'll talk about it in the next lesson.

In [31]:
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])

In [32]:
w = (XTX_inv.dot(X.T)).dot(y)

In [33]:
w

array([ 0.19989598, 31.02612262, 31.65378877])

In [34]:
w[0]

0.19989598183185908